#ifndef MAC_PARAMS_H
#ifdef __cplusplus
extern "C" {
#endif
#define MAC_PARAMS_H

/**
 * -----------------------------------------------------------------------------
 * this documnet define these macros with machine model.
 * it contain update history list in the end of file.
 * -----------------------------------------------------------------------------
 * detail following macro definitions:
 *      EMV_TERMINAL_NUM   -- logical device quantity
 *      SM_VERSION_SN      -- the driver version, ESS-YYMMDD-F
 *                            the E indicator is emv version
 *                            the SS indicator is iso7816 version
 *                            the YYMMDD indicator is the compiled date of driver.
 *      SM_VERSION_FLAG    -- the F indicator, it's value is 'R' or 'D'
 *                            if it's 'R', means the driver has passed emv 
 *                            certification.   
 *                            if it's 'D', means the driver is developing step.
 *      HAS_HIGH_SAM_PATCH -- indicate driver whether contain high speed card 
 *                            patch or not.
 * NOTE that the compiled data of driver is automatically generated by PC softeware
 * 
 * =============================================================================   
 *   日期        作者                              更新内容           
 * -----------------------------------------------------------------------------
 * 2010-11-23    刘波                  SP30接口芯片更换为TDA8023的驱动发布
 * -----------------------------------------------------------------------------
 * 2010-11-24    许万通                emv_atr_parse函数中关于T=1的时序(bwt,cwt)
 *                                     计算公式修正。
 * -----------------------------------------------------------------------------  
 *
 * -----------------------------------------------------------------------------
 *
 * -----------------------------------------------------------------------------
 *
 * -----------------------------------------------------------------------------
 *
 * -----------------------------------------------------------------------------
 *
 * -----------------------------------------------------------------------------
 *
 * =============================================================================
 */
/**
 * pos machine model list
 */

#define MH1901_L      19010

#include "mac_model.h"

/**
 * system platform macro definitions
 */
#define SYS_LINUX       (  1  )  /* driver for linux */
#define SYS_MONITOR     (  2  )  /* driver for monitor */
#define SYS_PLATFORM    SYS_MONITOR
#define EMV_STD         (  1  )

#if SYS_PLATFORM == SYS_MONITOR
#define printk  printf
#include <string.h>
#if TARGET_MAC == MH1901_L
//#warning " Compiling MH_SMCU driver for Pax Monitor system!\r\n"
#else
#error " You must define machine model!\r\n "
#endif
#endif

#if SYS_PLATFORM == SYS_LINUX
#if TARGET_MAC == MH1901_L
#warning " Compiling MHSMCU driver for Linux system!\r\n"
#else
#error " You must define machine model, but you didn't defined!\r\n "
#endif
#endif

#if MAC_MODEL != TARGET_MAC
#error "The macro MAC_MODEL is not same with macro TARGET_MAC, Please check your Makefile and mac_params.h!"
#endif

/**
 * the list of percent machine model software version information and 
 * card sockets numbers.
 */
#if TARGET_MAC == MH1901_L
#define  EMV_TERMINAL_NUM       1
#define  SM_VERSION_SN          "112"
#define  SM_VERSION_FLAG        "R"
#define  HAS_HIGH_SAM_PATCH     0   
#define  MAX_SPEED_LTD          64
/**
 * Update List:
 * ------------------------------------------------------------------------
 * 2013-5-12  [110]   Link   created
 * ------------------------------------------------------------------------
 * 2010-10-13 [111]   Link   For MH chip serials.
 * ------------------------------------------------------------------------
 */
#endif

#ifdef __cplusplus
}
#endif
#endif
